### ISSUE TITLE
Demodulator does not work for 1070/1270 Hz

### ISSUE THREAD

**Issue by jremington** [cstroie/Bell103#2]
This is a great start on an Arduino compatible modem, but did you ever get this to work as a pair of modems?

The originating modem generates the correct signals, but when used as an answer modem, the demodulator cannot discriminate 1070 Hz from 1270 Hz. When the roles are swapped, the demodulator does discriminate 2025 and 2225 Hz, albeit with rather high error rate.

I tested the demodulator with a precision oscillator, and also simulated the decode process using the built waveform generator, but alas, the demodulator produces a high correlation for all input signals between about 1.0 and 1.4 kHz.  Modifying the delay queue length helps a bit, but does not solve the basic problem.

I'm thinking of replacing the demodulator with a discrete FT, but thought I'd check to see what you think.

Cheers!

**Comment by jremington** [comment]
Taking a hint from the MicroModem code at unsigned.io, I expanded the dyFIFO to 32 bytes and experimented with longer delay queues. Using a delay of 15 samples actually works to discriminate both 1070/1270 and 2025/2225, but 16 ((samples per bit/2 as recommended) does not. I don't yet  understand why this delay is so critical, but now I am confident that the problem can be fixed.

**Comment by cstroie** [comment]
Thank you for appreciation!

I did not build a second modem, only one prototype. But I tested it with a soundcard and software modems on Linux (like minimodem). It worked both ways in Bell103 and ITU V.21. Another signal source was the recording  "300bps N,8,1 (Terminal Mode or ASCII Download)" from the "Peace and Love, Inc." album of Information Society, a nice hidden message. It worked too.
My goal was to call BBSes on real phone numbers using Hangouts for calling (since calling was free for a while) such bbs.retrobattlestations.com. If you keep the carrier on while connecting, the answering modem will reply in Bell103. Well, it worked but not too great. The signal is distorted (the codec is heavily optimized for voice), there is no error correction and the connection is closed after just a few errors.
I planed to create or use a line transformer from an old phone or modem to connect to real landlines, but never did it. Needless to say there are no more landlines phones.

Regarding the software solutions, Arabell300 uses integer math, including fixed-point arithmetic. And I am not a mathematician, just ham radio with some extra hobbies. I can't explain why the delay queue length works, but I suppose there is a common denominator of the symbol length and number of half-periods when correlation starts to work. Since we use integer math, this might not be the first half-period. And the sampling frequency (9600 Hz) is not a multiple of any signal frequency. I think, with floating point it might be better but slower.

Anyway, if you can improve the project, please do it!

**Comment by jremington** [comment]
Thanks for your input!  Obviously this was a labor of love and the code is really nice. But, as you point out, dialups and BBs have all but disappeared. 

For my own understanding, and for the fun of it, I'll try to get a pair of these modems to talk to each other reliably, using the original integer math. If it works I'll deposit a (slightly) improved version of your project.

As an aside, projects like MicroModem, OpenModem, TrackUino, etc. are half duplex, and use a much wider range of MARK and SPACE (e.g. 1200 and 2200) frequencies, so the decoding problem is much simpler.

Best regards, Jim Remington
